import { FileDown } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { CourseRecord, DayKey, Period, ScheduleGrid, SemesterKey } from '@/types/schedule';
import { getSlotCourseId } from '@/utils/courseUtils';

type Props = {
  schedule: ScheduleGrid;
  courseMap: Record<string, CourseRecord>;
  gradeProfile: string;
  studentName: string;
};

const A_PERIODS: Period[] = [1, 2, 3, 4];
const B_PERIODS: Period[] = [5, 6, 7, 8];

const periodTimes: Record<number, string> = {
  1: '7:45-9:05',
  2: '9:15-10:35',
  3: '10:45-12:10',
  4: '12:55-2:15',
  5: '7:45-9:05',
  6: '9:15-10:35',
  7: '10:45-12:10',
  8: '12:55-2:15',
};

function getCourseCell(schedule: ScheduleGrid, courseMap: Record<string, CourseRecord>, sem: SemesterKey, day: DayKey, period: Period): string {
  const id = getSlotCourseId(schedule, sem, day, period);
  if (!id) return '';
  const course = courseMap[id];
  return course ? `${course.name}\n${course.teacher}` : '';
}

function exportPDF(schedule: ScheduleGrid, courseMap: Record<string, CourseRecord>, gradeProfile: string, studentName: string) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' });

  // Header
  doc.setFillColor(45, 74, 54); // garden-700
  doc.rect(0, 0, 280, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('TardyBell', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Timpanogos High School  |  2026-2027', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`${studentName}  |  Grade ${gradeProfile}`, 270, 12, { align: 'right' });

  doc.setTextColor(0, 0, 0);

  // Semester 1 table
  const sem1Y = 28;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Semester 1', 14, sem1Y);

  const sem1Body: string[][] = [];
  for (let i = 0; i < 4; i++) {
    const aPeriod = A_PERIODS[i];
    const bPeriod = B_PERIODS[i];
    sem1Body.push([
      `P${aPeriod}\n${periodTimes[aPeriod]}`,
      getCourseCell(schedule, courseMap, 'sem1', 'A', aPeriod),
      `P${bPeriod}\n${periodTimes[bPeriod]}`,
      getCourseCell(schedule, courseMap, 'sem1', 'B', bPeriod),
    ]);
  }

  autoTable(doc, {
    startY: sem1Y + 2,
    head: [['Period', 'A-Day', 'Period', 'B-Day']],
    body: sem1Body,
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 89], textColor: 255, fontSize: 9, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 8, cellPadding: 3, minCellHeight: 14 },
    columnStyles: {
      0: { cellWidth: 22, halign: 'center', fontStyle: 'bold', fillColor: [253, 248, 235] },
      1: { cellWidth: 100 },
      2: { cellWidth: 22, halign: 'center', fontStyle: 'bold', fillColor: [240, 245, 241] },
      3: { cellWidth: 100 },
    },
    margin: { left: 14, right: 14 },
  });

  // Semester 2 table
  const sem2Y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Semester 2', 14, sem2Y);

  const sem2Body: string[][] = [];
  for (let i = 0; i < 4; i++) {
    const aPeriod = A_PERIODS[i];
    const bPeriod = B_PERIODS[i];
    sem2Body.push([
      `P${aPeriod}\n${periodTimes[aPeriod]}`,
      getCourseCell(schedule, courseMap, 'sem2', 'A', aPeriod),
      `P${bPeriod}\n${periodTimes[bPeriod]}`,
      getCourseCell(schedule, courseMap, 'sem2', 'B', bPeriod),
    ]);
  }

  autoTable(doc, {
    startY: sem2Y + 2,
    head: [['Period', 'A-Day', 'Period', 'B-Day']],
    body: sem2Body,
    theme: 'grid',
    headStyles: { fillColor: [74, 124, 89], textColor: 255, fontSize: 9, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 8, cellPadding: 3, minCellHeight: 14 },
    columnStyles: {
      0: { cellWidth: 22, halign: 'center', fontStyle: 'bold', fillColor: [253, 248, 235] },
      1: { cellWidth: 100 },
      2: { cellWidth: 22, halign: 'center', fontStyle: 'bold', fillColor: [240, 245, 241] },
      3: { cellWidth: 100 },
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const footerY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by TardyBell - tardybell.t8rsk8s.io', 14, footerY);

  const fileName = `${studentName.replace(/\s+/g, '_')}_Schedule_2026-2027.pdf`;
  doc.save(fileName);
}

export function ExportSchedule({ schedule, courseMap, gradeProfile, studentName }: Props) {
  return (
    <button
      onClick={() => exportPDF(schedule, courseMap, gradeProfile, studentName)}
      className="flex items-center gap-2 px-4 py-2 bg-garden-500 text-white rounded-lg hover:bg-garden-600 transition-colors text-sm font-medium shadow-sm"
    >
      <FileDown className="h-4 w-4" />
      Download PDF
    </button>
  );
}
